### ISSUE TITLE
bstreamer does not work with janus webrtc gateway

### ISSUE THREAD

**Issue by munishmahajan** [vzhn/bstreamer#2]
I am testing bstreamer with janus webrtc gateway. Able to negotiate but janus gateway does not receive streaming packets after negotiation. However it works fine with VLC and ffplay. Tried to find in code what is the streaming port? server.yaml seems to have negotiation port but not streaming port. Pl. help me to know streaming port?

**Comment by munishmahajan** [comment]
further digging down i found there is server_port missing in SETUP response. there should be 2 port numbers i.e. RTP and RTCP. What are these 2 ports?

**Comment by vzhn** [comment]
Hello! Thank you for posting issue.

**bstreamer** is working only in RTSP _interleaved_ mode: when RTSP, RTP and RTCP are sharing same connection.

Is janus webrtc software able to connect using an interleaved mode?

**Comment by vzhn** [comment]
Well, it seems like janus software did nod support interleaved mode: https://github.com/meetecho/janus-gateway/issues/1218#issuecomment-384916942

**Comment by munishmahajan** [comment]
yes, you are right. thanx for the help.
