### ISSUE TITLE
suggestions to Dockerize this app

### ISSUE THREAD

**Issue by yashkaransingh** [vzhn/bstreamer#9]
Hi @vzhn , can you suggest an approach on how to easily run this application on docker containers?

**Comment by vzhn** [comment]
Sorry, I am not docker user.

**Comment by luislobo** [comment]
Here you can find one Dockerfile 

https://github.com/iaroki/dockerfiles/tree/master/bstreamer

**Comment by yashkaransingh** [comment]
thanks @luislobo ,appreciate it
